from enum import IntEnum

class RETRO_DEVICE(IntEnum):
    NONE = 0
    JOYPAD = 1
    MOUSE = 2
    KEYBOARD = 3
    LIGHTGUN = 4
    ANALOG = 5
    POINTER = 6

class RETRO_INPUT(IntEnum):
    pass

class RETRO_INPUT_JOYPAD(RETRO_INPUT):
    B = 0
    Y = 1
    SELECT = 2
    START = 3
    UP = 4
    DOWN = 5
    LEFT = 6
    RIGHT = 7
    A = 8
    X = 9
    L = 10
    R = 11
    L2 = 12
    R2 = 13
    L3 = 14
    R3 = 15
    MASK = 256

class RETRO_INPUT_ANALOG_INDEX(RETRO_INPUT):
    LEFT = 0
    RIGHT = 1
    BUTTON = 2

class RETRO_INPUT_ANALOG(RETRO_INPUT):
    X = 0
    Y = 1

class RETRO_INPUT_MOUSE(RETRO_INPUT):
    X = 0
    Y = 1
    LEFT = 2
    RIGHT = 3
    WHEELUP = 4
    WHEELDOWN = 5
    MIDDLE = 6
    HORIZ_WHEELUP = 7
    HORIZ_WHEELDOWN = 8
    BUTTON_4 = 9
    BUTTON_5 = 10

class RETRO_INPUT_LIGHTGUN(RETRO_INPUT):
    ...

class RETRO_INPUT_POINTER(RETRO_INPUT):
    ...


class RETRO_COLOR_FORMAT(IntEnum):
    FORMAT_0RGB1555 = 0
    FORMAT_XRGB8888 = 1
    FORMAT_RGB565 = 2
    FORMAT_UNKNOWN = -1


class RETRO_LOG_LEVEL(IntEnum):
    DEBUG = 0
    INFO = 1
    WARN = 2
    ERROR = 3
    DUMMY = -1


RETRO_ENVIRONMENT_EXPERIMENTAL = 0x10000
RETRO_ENVIRONMENT_PRIVATE = 0x20000

class RETRO_ENVIRONMENT(IntEnum):
    SET_ROTATION = 1
    GET_OVERSCAN = 2
    GET_CAN_DUPE = 3
    SET_MESSAGE = 6
    SHUTDOWN = 7
    SET_PERFORMANCE_LEVEL = 8
    GET_SYSTEM_DIRECTORY = 9
    SET_PIXEL_FORMAT = 10
    SET_INPUT_DESCRIPTORS = 11
    SET_KEYBOARD_CALLBACK = 12
    SET_DISK_CONTROL_INTERFACE = 13
    SET_HW_RENDER = 14
    GET_VARIABLE = 15
    SET_VARIABLES = 16
    GET_VARIABLE_UPDATE = 17
    SET_SUPPORT_NO_GAME = 18
    GET_LIBRETRO_PATH = 19
    SET_FRAME_TIME_CALLBACK = 21
    SET_AUDIO_CALLBACK = 22
    GET_RUMBLE_INTERFACE = 23
    GET_INPUT_DEVICE_CAPABILITIES = 24
    GET_SENSOR_INTERFACE = 25 | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_CAMERA_INTERFACE = 26 | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_LOG_INTERFACE = 27
    GET_PERF_INTERFACE = 28
    GET_LOCATION_INTERFACE = 29
    # GET_CONTENT_DIRECTORY = 30
    GET_CORE_ASSETS_DIRECTORY = 30
    GET_SAVE_DIRECTORY = 31
    SET_SYSTEM_AV_INFO = 32
    SET_PROC_ADDRESS_CALLBACK = 33
    SET_SUBSYSTEM_INFO = 34
    SET_CONTROLLER_INFO = 35
    SET_MEMORY_MAPS = 36 | RETRO_ENVIRONMENT_EXPERIMENTAL
    SET_GEOMETRY = 37
    GET_USERNAME = 38
    GET_LANGUAGE = 39
    GET_CURRENT_SOFTWARE_FRAMEBUFFER = 40 | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_HW_RENDER_INTERFACE = 41
    SET_SUPPORT_ACHIEVEMENTS = 42 | RETRO_ENVIRONMENT_EXPERIMENTAL
    SET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE = 43 | RETRO_ENVIRONMENT_EXPERIMENTAL
    SET_SERIALIZATION_QUIRKS = 44 | RETRO_ENVIRONMENT_EXPERIMENTAL
    SET_HW_SHARED_CONTEXT = 44 | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_VFS_INTERFACE = 45 | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_LED_INTERFACE = 46 | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_AUDIO_VIDEO_ENABLE = 47 | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_MIDI_INTERFACE = 48 | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_FASTFORWARDING = 49 | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_TARGET_REFRESH_RATE = 50 | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_INPUT_BITMASKS = 51 | RETRO_ENVIRONMENT_EXPERIMENTAL
    GET_CORE_OPTIONS_VERSION = 52
    SET_CORE_OPTIONS = 53
    SET_CORE_OPTIONS_INTL = 54
    SET_CORE_OPTIONS_DISPLAY = 55
    GET_PREFERRED_HW_RENDER  = 56
    GET_DISK_CONTROL_INTERFACE_VERSION = 57
    SET_DISK_CONTROL_EXT_INTERFACE = 58
    GET_MESSAGE_INTERFACE_VERSION = 59
    SET_MESSAGE_EXT = 60
    GET_INPUT_MAX_USERS = 61
    SET_AUDIO_BUFFER_STATUS_CALLBACK = 62
    SET_MINIMUM_AUDIO_LATENCY = 63
    SET_FASTFORWARDING_OVERRIDE = 64
    SET_CONTENT_INFO_OVERRIDE = 65
    GET_GAME_INFO_EXT = 66
    SET_CORE_OPTIONS_V2 = 67
    SET_CORE_OPTIONS_V2_INTL = 68
    SET_CORE_OPTIONS_UPDATE_DISPLAY_CALLBACK = 69
    SET_VARIABLE = 70
    GET_THROTTLE_STATE = 71 | RETRO_ENVIRONMENT_EXPERIMENTAL


class RETRO_REGION(IntEnum):
    NTSC = 0
    PAL = 1