site_name: RetroPy - Documentation
site_url: https://29th-Day.github.io/retropy/
repo_url: https://github.com/29th-Day/retropy
repo_name: 29th-Day/retropy

nav:
  - index.md
  - installation.md
  - Tutorials:
      - tutorials/index.md
      - tutorials/getting-started.md
      - tutorials/frontends.md
      - tutorials/customization.md
  - how-to-guides.md
  - Code Reference: reference/
  - mkdocs.md

watch:
  - src

plugins:
  - search
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md

theme:
  favicon: img/favicon.ico
  logo: img/logo.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system mode
      primary: purple
      accent: lime
      
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: purple
      accent: teal

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/29th-Day
  # version:
  #   provider: mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://github.com/29th-Day" target="_blank" rel="noopener">29th-Day</a>
