# libretro.h

from enum import IntEnum

# region 259-299

class Language(IntEnum):
    ENGLISH = 0
    JAPANESE = 1
    FRENCH = 2
    SPANISH = 3
    GERMAN = 4
    ITALIAN = 5
    DUTCH = 6
    PORTUGUESE_BRAZIL = 7
    PORTUGUESE_PORTUGAL = 8
    RUSSIAN = 9
    KOREAN = 10
    CHINESE_TRADITIONAL = 11
    CHINESE_SIMPLIFIED = 12
    ESPERANTO = 13
    POLISH = 14
    VIETNAMESE = 15
    ARABIC = 16
    GREEK = 17
    TURKISH = 18
    SLOVAK = 19
    PERSIAN = 20
    HEBREW = 21
    ASTURIAN = 22
    FINNISH = 23
    INDONESIAN = 24
    SWEDISH = 25
    UKRAINIAN = 26
    CZECH = 27
    CATALAN_VALENCIA = 28
    CATALAN = 29
    BRITISH_ENGLISH = 30
    HUNGARIAN = 31
    BELARUSIAN = 32

# endregion
